HAI 1.2

I HAS A HOURS
GIMMEH HOURS
I HAS A MINUTES
GIMMEH MINUTES
I HAS A DELAY
GIMMEH DELAY

MINUTES R SUM OF MINUTES AN DELAY
BOTH SAEM MINUTES AN BIGGR OF MINUTES AN 59, O RLY?
YA RLY
    MINUTES R MOD OF MINUTES AN 60
    HOURS R SUM OF HOURS AN 1
OIC

BOTH SAEM HOURS AN BIGGR OF HOURS AN 23, O RLY?
YA RLY
    HOURS R MOD OF HOURS AN 24
OIC

VISIBLE HOURS "::" MINUTES

KTHXBYE