HAI 1.2

I HAS A GRADE
GIMMEH GRADE
GRADE IS NOW A NUMBAR

BOTH SAEM GRADE AN SMALLR OF GRADE AN 5, O RLY?
YA RLY
VISIBLE "suspens"
MEBBE BOTH SAEM GRADE AN SMALLR OF GRADE AN 7
VISIBLE "aprovat"
MEBBE BOTH SAEM GRADE AN SMALLR OF GRADE AN 9
VISIBLE "notable"
MEBBE DIFFRINT GRADE AN BIGGR OF GRADE AN 10
VISIBLE "excel.lent"
NO WAI
VISIBLE "MH"
OIC

KTHXBYE