HAI 1.2

I HAS A HOUR
GIMMEH HOUR
I HAS A MINUTE
GIMMEH MINUTE
MINUTE IS NOW A NUMBR

HOUR R PRODUKT OF 5 AN MOD OF HOUR AN 12

DIFFRINT HOUR AN SMALLR OF HOUR AN MINUTE, O RLY?
YA RLY
    VISIBLE "hour hand"
MEBBE DIFFRINT MINUTE AN SMALLR OF HOUR AN MINUTE
    VISIBLE "minute hand"
NO WAI
    VISIBLE "draw"
OIC

KTHXBYE