HAI 1.2

I HAS A AH
GIMMEH AH
AH IS NOW A NUMBR
I HAS A BEE
GIMMEH BEE
BEE IS NOW A NUMBR
I HAS A SEE
GIMMEH SEE
SEE IS NOW A NUMBR
I HAS A DEE
GIMMEH DEE
DEE IS NOW A NUMBR

I HAS A COND1 ITZ BOTH SAEM DEE AN BIGGR OF AH AN DEE
I HAS A COND2 ITZ BOTH SAEM BEE AN BIGGR OF BEE AN SEE

BOTH OF COND1 AN COND2, O RLY?
YA RLY
    I HAS A LOW ITZ BIGGR OF AH AN SEE
    I HAS A HIGH ITZ SMALLR OF BEE AN DEE
    VISIBLE "WIN " LOW " " HIGH
NO WAI
    VISIBLE "FAIL " 1 " " 0
OIC

KTHXBYE