HAI 1.2

I HAS A YEAR
GIMMEH YEAR

BOTH SAEM 0 AN MOD OF YEAR AN 400, O RLY?
YA RLY
    VISIBLE "WIN"
MEBBE BOTH SAEM 0 AN MOD OF YEAR AN 100
    VISIBLE "FAIL"
MEBBE BOTH SAEM 0 AN MOF OF YEAR AN 4
    VISIBLE "WIN"
NO WAI
    VISIBLE "FAIL"
OIC

KTHXBYE