HAI 1.2

I HAS A TIME
GIMMEH TIME
MAEK TIME A NUMBR

I HAS A SECONDS ITZ MOD OF TIME AN 60
I HAS A MINUTES ITZ QUOSHUNT OF DIFF OF MOD OF TIME AN 3600 AN SECONDS AN 60
I HAS A HOURS ITZ QUOSHUNT OF DIFF OF TIME AN MOD OF TIME AN 3600 AN 3600

VISIBLE HOURS "::" MINUTES "::" SECONDS

KTHXBYE